{{ if .Values.ai.enabled }}
{{ $fullname := include "brigade.ai.fullname" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ template "brigade.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: gateway
    type: ai-training
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "brigade.fullname" . }}
        role: gateway
        type: ai-training
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ai.registry }}/{{ .Values.ai.name }}:{{ default .Chart.AppVersion .Values.ai.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.ai.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ai.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.ai.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.ai.service.internalPort }}
        env:
          - name: BRIGADE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}
{{ end }}
